name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]

executables = ["example"]

[[depends-on]]
tux = "*"

[[pins]]
tux = { path = "../.." }

[configuration.values]
tux.SHA256_Backend = "Speed"