name = "prove"
description = "Project to prove Tux"
version = "0.1.0-dev"

authors = ["Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]

[[depends-on]]
tux = "*"
gnatprove = "=12.1.1"

[[pins]]
tux = { path = ".." }