on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
    branches:
      - main
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  build-and-test:
    strategy:
      fail-fast: false # Don't stop all the workflows when one of them fails.

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0

      # Install and setup PyTest to run the test vectors
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Test Dependencies
        run: |
          pip install -r tests/requirements.txt

      # Build the project using the validation build profile to enforce
      # static analysis and coding style.
      - name: Build
        run: |
          alr build --validation

      - name: Build Tests
        run: |
          cd tests
          python make_build_crate.py --output-dir=test_crate --tux-build-profile=validation --unit-tests-report-format=XML
          cd test_crate
          alr build

      - name: Run Known Answer Tests
        run: |
          cd tests
          pytest kat -n logical --html=kat_report.html --self-contained-html --junitxml=kat.xml

      - name: Run Unit Tests
        run: |
          cd tests
          unit_tests/bin/unit_tests > unit_tests.xml