on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
    branches:
      - main
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  build-and-test:
    strategy:
      fail-fast: false # Don't stop all the workflows when one of them fails.

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0

      # Install and setup PyTest to run the test vectors
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Build the project using the validation build profile to enforce
      # static analysis and coding style.
      - name: Build
        run: |
          alr build --validation

      # Build and run the benchmark program
      # Note that the benchmark measurements are unlikely to be fully
      # representative due to interference from other processes on the CI
      # runner, but the purpose of this check is to ensure that the benchmark
      # builds and runs without errors.
      - name: Run Benchmark
        run: |
          cd tests/benchmark
          alr build --validation
          alr build --release
          alr run -s

      # Build and run the Known Answer Tests
      - name: Run Test Vectors
        run: |
          pip install pytest
          cd tests/kat
          ./build-programs.sh
          pytest -n logical .

      # Build and run the unit tests
      - name: Run Unit Tests
        run: |
          cd tests/unit_tests
          alr build --validation
          alr run -s